apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: registry-server
  template:
    metadata:
      labels:
        app: registry-server
    spec:
      containers:
      - name: registry-server
        image: registry:2.8.2
        ports:
        - containerPort: 5000
        env:
        - name: REGISTRY_HTTP_HEADERS_Access-Control-Allow-Origin
          value: '[http://registry.example.com]'
        - name: REGISTRY_HTTP_HEADERS_Access-Control-Allow-Methods
          value: '[HEAD,GET,OPTIONS,DELETE]'
        - name: REGISTRY_HTTP_HEADERS_Access-Control-Allow-Credentials
          value: '[true]'
        - name: REGISTRY_HTTP_HEADERS_Access-Control-Allow-Headers
          value: '[Authorization,Accept,Cache-Control]'
        - name: REGISTRY_HTTP_HEADERS_Access-Control-Expose-Headers
          value: '[Docker-Content-Digest]'
        - name: REGISTRY_STORAGE_DELETE_ENABLED
          value: 'true'
        volumeMounts:
        - name: registry-data
          mountPath: /var/lib/registry
      volumes:
      - name: registry-data
        persistentVolumeClaim:
          claimName: registry-data-pvc
