// Generated by Riju Vijayan, assisted by ZCoder on 17-January-2025 <Please retain this marker>

import app from "./app";

const port = 3000;

app.listen(port, () => {
  console.log(`Client app listening on port ${port}`);
});
