kind: TestWorkflow
apiVersion: testworkflows.testkube.io/v1
metadata:
  name: e2e-playwright-workflow
  namespace: testkube
  labels:
    app.kubernetes.io/instance: testkube-workflow
    docs: example
spec:
  config:
    SUITE_NAME:
      type: string
      default: smoke
  container:
    workingDir: /e2e
    image: rijuvijayan/pw-e2e
    imagePullPolicy: Always
    resources:
      requests:
        cpu: 2
        memory: 2Gi
  steps:
    - name: Run tests
      shell: |
        pnpm run test:{{ config.SUITE_NAME }}
        cp -r ${PWD}/playwright-report /data/playwright-report
    - name: Uploading test results
      artifacts:
        paths:
          - /data/playwright-report/**/*
