kind: TestWorkflow
apiVersion: testworkflows.testkube.io/v1
metadata:
  name: e2e-playwright-workflow
  namespace: testkube
  labels:
    docs: example
spec:
  container:
    container:
    workingDir: /e2e
    image: rijuvijayan/pw-e2e
    resources:
      requests:
        cpu: 2
        memory: 2Gi
  steps:
    - name: Run tests
      shell: pnpm run test:smoke
      artifacts:
      paths:
        - playwright-report/**/*
