kind: TestWorkflow
apiVersion: testworkflows.testkube.io/v1
metadata:
  name: basic-playwright-workflow
  namespace: testkube
  labels:
    docs: example
spec:
  content:
    git:
      uri: https://github.com/rijuvijayan87/e2e-tests-infra
      revision: main
      paths:
        - test
  container:
    container:
    workingDir: /e2e
    image: rijuvijayan/pw-e2e
    resources:
      requests:
        cpu: 2
        memory: 2Gi
  steps:
    - name: Run tests
      shell: test --grep=@sanity
      artifacts:
        paths:
          - playwright-report/**/*
status: {}
