apiVersion: batch/v1
kind: Job
metadata:
  generateName: pw-e2e-
spec:
  template:
    spec:
      containers:
        - name: pw-e2e
          image: rijuvijayan/pw-e2e
      restartPolicy: Never
      ttlSecondsAfterFinished: 300
  backoffLimit: 4
