apiVersion: batch/v1/Job:pw-e2e
kind: Job
metadata:
  name: pw-e2e
spec:
  template:
    spec:
      containers:
      - name: pw-e2e
        image: rijuvijayan/pw-e2e
      restartPolicy: Never
  backoffLimit: 4


