apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argocd-job-patcher
  namespace: e2e-tests
rules:
  - apiGroups:
      - batch
    resources:
      - jobs
    verbs:
      - patch
