apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argocd-configmap-patcher
  namespace: e2e-tests
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - patch
