apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argocd-job-creator
  namespace: default
rules:
  - apiGroups:
      - batch
    resources:
      - jobs
      - persistentvolumeclaims
    verbs:
      - create
      - update
      - delete
