apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-app
  namespace: client-endpoints
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client-app
  template:
    metadata:
      labels:
        app: client-app
    spec:
      containers:
        - name: client-app
          image: rijuvijayan/app-client:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi
          env:
            - name: EXPRESS_SERVER_URL
              value: "http://server-app.server-endpoints.svc.cluster.local:9222"
