apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-app
  namespace: server-endpoints
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server-app
  template:
    metadata:
      labels:
        app: server-app
    spec:
      containers:
        - name: server-app
          image: rijuvijayan/app-server:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 9222
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi
